services:
  postgres:
    image: postgres:15
    container_name: food_quality_db_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: bloodlaac
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: food_quality_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: